M48
; DRILL file {KiCad 8.0.6} date 2025-03-18T08:59:13+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-18T08:59:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.1955Y-5.4173
X5.3864Y-5.4173
T2
X5.1837Y-5.5366
X5.3982Y-5.5366
M30
